# config file

#get quote config. document: https://forismatic.com/en/api/
quoteServerUrl: "http://api.forismatic.com/api/1.0/"
quoteMethod: "getQuote"
quoteFormat: "json"
quoteLang: "en"


#get picture
pictureServerUrl: "https://picsum.photos"
pictureWidth: "500"
pictureHeight: "300"
pictureBackupUrl:
  - "http://127.0.0.1:8080/image/backup1.jpg"
  - "http://127.0.0.1:8080/image/backup2.jpg"